-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 15:53:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb3 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`prio_priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`prio_priority` (
  `PRIO_ID` INT NOT NULL AUTO_INCREMENT,
  `PRIO_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `PRIO_DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PRIO_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test`.`stat_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`stat_status` (
  `STAT_ID` INT NOT NULL,
  `STAT_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `STAT_DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`STAT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test`.`task_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`task_task` (
  `TASK_ID` INT NOT NULL AUTO_INCREMENT,
  `TASK_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `TASK_DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL,
  `TASK_BEGIN_DATE` DATETIME NULL DEFAULT NULL,
  `TASK_END_DATE` DATETIME NULL DEFAULT NULL,
  `STAT_ID` INT NOT NULL,
  `PRIO_ID` INT NOT NULL,
  PRIMARY KEY (`TASK_ID`),
  INDEX `fk_TASK_TASK_STAT_STATUS_idx` (`STAT_ID` ASC) VISIBLE,
  INDEX `fk_TASK_TASK_PRIO_PRIORITY1_idx` (`PRIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TASK_TASK_PRIO_PRIORITY1`
    FOREIGN KEY (`PRIO_ID`)
    REFERENCES `test`.`prio_priority` (`PRIO_ID`),
  CONSTRAINT `fk_TASK_TASK_STAT_STATUS`
    FOREIGN KEY (`STAT_ID`)
    REFERENCES `test`.`stat_status` (`STAT_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
